---
title: "Presentations"
---

### 2021

#### November 2021. **"Long-Term Shifts in the Fish and Macroinvertebrate Community in a Mid-Atlantic Estuary"**
*American Fisheries Society Annual Conference*

#### September 2021. **"Changes in a Mid Atlantic Estuary: Long Term Shifts in the Fish and Macroinvertebrate Community in Delaware Bay"**
*NOAA Central Library* 

<iframe width="560" height="315" src="https://www.youtube.com/embed/nLMJUsBPewM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 2020

#### September 2021. **"Long-Term Shifts in the Fish and Macroinvertebrate Community in a North American Estuary"**
*World Fisheries Congress*

#### November 2020. **"Changes in a Mid-Atlantic Estuary: Long-Term Trends in Environmental Conditions and Marine Community in Delaware Bay"**
*American Fisheries Society Mid-Atlantic Chapter Meeting*

### 2019

#### November 2019. **“Factors Influencing Community Composition in Delaware Bay”**
*American Fisheries Society Mid-Atlantic Chapter Meeting*

#### March 2019. **“Changes in Fish and Invertebrate Assemblages and Overall Community Composition in Delaware Bay”**
*University of Delaware College of Earth, Ocean, and Environment Graduate Student Research Symposium*